name: CI Tests

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: |
          yarn install
      - name: yarn test
        run: |
          yarn test
        env:
          CI: true
					SKIP_PREFLIGHT_CHECK: true
