name: CI Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: |
          yarn install
      - name: yarn test
        run: |
          yarn test
        env:
          CI: true
      - name: yarn deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: development
          REACT_APP_AUTH0_DOMAIN: react-rb-auth.eu.auth0.com
          REACT_APP_AUTH0_CLIENT_ID: IQHjsH8rbRctSLd2dqErP3SC6WJ4mqx5
          REACT_APP_AUTH0_AUDIENCE: https://react-rb-auth.eu.auth0.com/api/v2/
          CI: true
